CourseProject/CourseProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('django/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CourseProject/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index ),
    path('candidates/', views.candidates),
    path('workers/', views.workers),
    path('orders/', views.orders),
    path('worker/<int:id>', views.concrete_worker),
    path('candidate/<int:id>', views.concrete_candidate),
    path('edit/<int:id>', views.edit_worker),
    path('profile/<int:id>', views.profile),
    path('candidate_page/<int:id>', views.candidate_page),


]

CourseProject/users/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/',  auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('register/', views.register, name='register'),
]

CourseProject/main/forms.py
from django import forms
from django.forms import DateInput, NumberInput, DateField
from .models import *
from django.forms import ModelForm, TextInput, FileInput
from itertools import chain

class WorkerForm(ModelForm):
    class Meta:
        model = Worker
        fields = '__all__'
        widgets = {
            'photo': FileInput(attrs={
                'accept': 'image/*',
                'required': 'False',
          }),
            'surname': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите фамилию..',
                'id': 'surname',
                'name': 'surname'
            }),
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите имя..',
                'id': 'name',
                'name': 'name'
            }),
            'patronymic': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите фамилию..',
                'id': 'patronymic',
                'name': 'patronymic'
            }),
            'gender': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите пол..',
                'id': 'gender',
                'name': 'gender'
            }),
            'birthday': DateInput(attrs={
                'class': 'form-control',
                'id': 'birthday',
                'name': 'birthday'
            }),
            'work_experience': NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите опыт работы..',
                'id': 'work_experience',
                'name': 'work_experience'
            }),
            'adress': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите адрес..',
            }),
            'phone_number': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите номер..',
                'id': 'phone_number',
                'name': 'phone_number'
            }),

        }

class ResumeForm(ModelForm):
    class Meta:
        model = Worker
        fields = '__all__'
        widgets = {
            'photo': FileInput(attrs={
                'accept': 'image/*',
                'required': 'False',
          }),
            'surname': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите фамилию..',
                'id': 'surname',
                'name': 'surname'
            }),
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите имя..',
                'id': 'name',
                'name': 'name'
            }),
            'patronymic': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите фамилию..',
                'id': 'patronymic',
                'name': 'patronymic'
            }),
            'gender': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите пол..',
                'id': 'gender',
                'name': 'gender'
            }),
            'birthday': DateInput(attrs={
                'class': 'form-control',
                'id': 'birthday',
                'name': 'birthday'
            }),
            'work_experience': NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите опыт работы..',
                'id': 'work_experience',
                'name': 'work_experience'
            }),
            'adress': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите адрес..',
            }),
            'phone_number': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите номер..',
                'id': 'phone_number',
                'name': 'phone_number'
            }),
            'position': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите желаемую позицицю..',
                'id': 'position',
                'name': 'position'
            }),
        }


class OrderForm(forms.Form):
    orderNumber = forms.IntegerField(label='Номер приказа', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Введите номер приказа'}))
    orderType = forms.ChoiceField(label='Выбор типа приказа', choices=[('', 'Выберите тип приказа'), (1, 'Отпуск'), (2, 'Прием на работу'), (3, 'Увольнение')], widget=forms.Select(attrs={'class': 'form-control'}))
    vacationType = forms.ModelChoiceField(required=False, queryset=VacationType.objects.all(), label='Тип отпуска',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    employee = forms.ModelChoiceField( required=False, queryset=Worker.objects.all(), label='Сотрудник',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    startDate = forms.DateField(required=False, label='Дата начала отпуска', widget=forms.DateInput(attrs={'class': 'form-control'}))
    endDate = forms.DateField(required=False, label='Дата окончания отпуска', widget=forms.DateInput(attrs={'class': 'form-control'}))
    candidate = forms.ModelChoiceField(required=False, queryset=JobResume.objects.all(), label='Кандидат',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    dismissalEmployee = forms.ModelChoiceField(required=False, queryset=Worker.objects.all(), label='Сотрудник',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    reason = forms.CharField(required=False, label='Причина увольнения', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите причину увольнения'}))
    salary = forms.IntegerField(required=False, label='Оклад', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите оклад'}))
    pow = forms.CharField(required=False, label='Место работы', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите место работы'}))
    subdivision = forms.CharField(required=False, label='Подразделение', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите подразделение'}))
    job_title = forms.CharField(required=False, label='Должность', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите должность'}))


class ContractForm(forms.Form):
    worker = forms.ModelChoiceField(queryset=Worker.objects.all(), label='Сотрудник',
                                      widget=forms.Select(attrs={'class': 'form-control'}))
    receipt_date = forms.DateField(label='Дата заключения',
                                widget=forms.DateInput(attrs={'class': 'form-control'}))
    salary = forms.IntegerField(label='Оклад', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите оклад'}))
    pow = forms.CharField(label='Место работы', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите место работы'}))
    subdivision = forms.CharField(label='Подразделение', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите подразделение'}))
    job_title = forms.CharField(label='Должность', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите должность'}))

class SickLeaveForm(forms.Form):
    startDate = forms.DateField(required=False, label='Дата начала больничного',
                                widget=forms.DateInput(attrs={'class': 'form-control'}))
    endDate = forms.DateField(required=False, label='Дата окончания больничного',
                              widget=forms.DateInput(attrs={'class': 'form-control'}))

CourseProject/main/templates/main/candidate_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'main/css/concrete_worker.css' %}">
  <title></title>
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/candidates/">Кандидаты</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/workers/">Сотрудники</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders/">Приказы</a>
        </li>
      </ul>
    </div>
    {% endif %}

    {% if request.user.is_authenticated %}
      <div>
        {% if request.user.id_role.name == 'Сотрудник' %}
        <a href="/profile/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5> </a>
        {% elif  request.user.id_role.name == 'Кандидат' %}
        <a href="/candidate_page/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5></a>
        {% else %}
           <h5>{{request.user.username}}</h5></a>
        {% endif %}

        </a>
      </div>

      <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary ml-2">Выйти</button>
      </form>

    {% else %}
      <a href="/users/login/"><button class="btn btn-outline-primary ml-2">Войти</button></a>
      <a href="{% url 'users:register' %}"><button class="btn btn-outline-primary ml-2">Регистрация</button></a>
    {% endif %}

  </nav>

  <div class="container">
    <h1>Здравствуйте, {{user_data.name}} {{user_data.patronymic}} !</h1><br>
    <div class="row">
      <div class="col-md-6">
      <h2>Личная информация</h2>
        <div class="form-group">
          <label for="photo">Фотография</label>
         {% if user_data.photo != null and user_data.photo != '' %}
          <img src="{{user_data.photo.url}}" alt="Фотография " class="img-fluid">
          {% else %}
          <img src="{% static 'main/img/worker.png' %}" alt="Фотография" class="img-fluid">
          {% endif %}
        </div>
        <div class="form-group">
          <label for="fullName">ФИО</label>
          <p> {{user_data.surname}} {{user_data.name}}  {{user_data.patronymic}}</p>
        </div>
        <div class="form-group">
          <label for="dob">Дата рождения</label>
          <p> {{user_data.birthday}}</p>
        </div>
        <div class="form-group">
          <label for="gender">Пол</label>
          <p> {{user_data.gender}}</p>
        </div>
        <div class="form-group">
          <label for="address">Адрес</label>
          <p> {{user_data.adress}}</p>
        </div>
        <div class="form-group">
          <label for="experience">Опыт работы</label>
          <p> {{user_data.work_experience}}</p>
        </div>
        <div class="form-group">
          <label for="phone">Номер телефона</label>
          <p> {{user_data.phone_number}}</p>
        </div>
        <a href="/edit/{{user_data.id_worker}}"><button class="btn btn-primary">Редактировать</button></a>
      </div>
      <div class="col-md-6">
        <h2>Рабочая информация</h2>
        <div class="form-group">
          <label for="department">Желаемая должность</label>
          <p>{{user_data.position}}</p>
        </div>
         <h2>Данные об образовании</h2>
          {% if educations|length > 0 %}
          {% for el in educations %}
            <div class="form-group">
              <label for="department">Название заведения</label>
              <p>{{el.educational_institute}}</p>
            </div>
            <div class="form-group">
              <label >Дата начала</label>
              <p>{{el.receipt_date}}</p>
            </div>
             <div class="form-group">
              <label >Дата окончания</label>
              <p>{{el.expiration_date}}</p>
            </div>
          {% endfor %}
          {% else %}
            <p>Данные об образовании отсутсвуют</p>
        {% endif %}
      </div>
    </div>


  </div>
</body>
</html>

CourseProject/main/templates/main/candidates.html
 {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Обязательные метатеги для мобильного масштабирования -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Подключение Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'main/css/orders.css' %}">
  <title>Страница сотрудников</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/candidates/">Кандидаты</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/workers/">Сотрудники</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders/">Приказы</a>
        </li>
      </ul>
    </div>
    {% endif %}

     {% if request.user.is_authenticated %}
      <div>
        {% if request.user.id_role.name == 'Сотрудник' %}
        <a href="/profile/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5> </a>
        {% elif  request.user.id_role.name == 'Кандидат' %}
        <a href="/candidate_page/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5></a>
        {% else %}
           <h5>{{request.user.username}}</h5></a>
        {% endif %}

        </a>
      </div>

      <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary ml-2">Выйти</button>
      </form>

    {% else %}
      <a href="/users/login/"><button class="btn btn-outline-primary ml-2">Войти</button></a>
      <a href="{% url 'users:register' %}"><button class="btn btn-outline-primary ml-2">Регистрация</button></a>
    {% endif %}

  </nav>

  <div class="container">
    <h1>Список кандидатов</h1>
    <hr>
    <div id="employeesList">
      {% for candidate in candidates %}
      <div class="candidate-item">
        <a href="/candidate/{{candidate.id}}"><h4>{{candidate.fio}}</h4></a>
        <p><strong>Должность:</strong> {{candidate.job}} </p>
      </div>
      <hr>
      {% endfor %}
    </div>
  </div>

  <!-- Подключение Bootstrap JS и jQuery (необходим для работы Bootstrap) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

CourseProject/main/templates/main/concrete_order.html
 {% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main/css/orders.css' %}">
  <title>Отображение документа</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/candidates/">Кандидаты</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/workers/">Сотрудники</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders/">Приказы</a>
        </li>
      </ul>
    </div>
    {% endif %}

    {% if request.user.is_authenticated %}
      <div>
        {% if request.user.id_role.name == 'Сотрудник' %}
        <a href="/profile/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5> </a>
        {% elif  request.user.id_role.name == 'Кандидат' %}
        <a href="/candidate_page/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5></a>
        {% else %}
           <h5>{{request.user.username}}</h5></a>
        {% endif %}

        </a>
      </div>

      <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary ml-2">Выйти</button>
      </form>

    {% else %}
      <a href="/users/login/"><button class="btn btn-outline-primary ml-2">Войти</button></a>
      <a href="{% url 'users:register' %}"><button class="btn btn-outline-primary ml-2">Регистрация</button></a>
    {% endif %}

  </nav>

  <div class="container">
    <h1>Приказ №1</h1>
    <div id="document-content">
      <!-- Содержимое документа будет получено с сервера и отображено здесь -->
    </div>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

CourseProject/main/templates/main/orders.html
 {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main/css/orders.css' %}">
  <title>Приказы</title>

</head>

<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/candidates/">Кандидаты</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/workers/">Сотрудники</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/orders/">Приказы</a>
        </li>
      </ul>
    </div>
    {% endif %}

     {% if request.user.is_authenticated %}
      <div>
        {% if request.user.id_role.name == 'Сотрудник' %}
        <a href="/profile/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5> </a>
        {% elif  request.user.id_role.name == 'Кандидат' %}
        <a href="/candidate_page/{{request.user.id_user}}">
          <h5>{{request.user.username}}</h5></a>
        {% else %}
           <h5>{{request.user.username}}</h5></a>
        {% endif %}

        </a>
      </div>

      <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary ml-2">Выйти</button>
      </form>

    {% else %}
      <a href="/users/login/"><button class="btn btn-outline-primary ml-2">Войти</button></a>
      <a href="{% url 'users:register' %}"><button class="btn btn-outline-primary ml-2">Регистрация</button></a>
    {% endif %}

  </nav>


  <div class="container">
    <div class="container">

       {% if request.user.id_role.name == 'Администратор' %}
       <div class="container" id="contract_form">
        <h2>Добавление нового трудового договора</h2>
        <form method="post">
          {% csrf_token %}
           <div class="form-group">
            <label>Сотрудник:</label>
            {{contractForm.worker}}
            {{contractForm.worker.errors}}
          </div>
          <div class="form-group">
            <label>Дата заключения:</label>
            {{contractForm.receipt_date}}
            {{contractForm.receipt_date.errors}}
          </div>
          <div class="form-group">
            <label>Оклад:</label>
            {{contractForm.salary}}
            {{contractForm.salary.errors}}
          </div>
           <div class="form-group">
            <label>Место работы:</label>
            {{contractForm.pow}}
            {{contractForm.pow.errors}}
          </div>
           <div class="form-group">
            <label>Подразделение:</label>
            {{contractForm.subdivision}}
            {{contractForm.subdivision.errors}}
          </div>
           <div class="form-group">
            <label>Должность:</label>
            {{contractForm.job_title}}
            {{contractForm.job_title.errors}}
          </div>
          <button type="submit" name="addContract" class="btn btn-primary">Добавить договор</button>
        </form>
      </div>

      <div class="container" id="order_form">
        <h2>Добавление нового приказа</h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="orderNumber">Номер приказа:</label>
            {{form.orderNumber}}
            {{form.orderNumber.errors}}
          </div>
          <div class="form-group">
            <label for="orderType">Выбор типа приказа:</label>
            {{form.orderType}}
            {{form.orderType.errors}}
            <!--<select class="form-control" id="orderType">
              <option value="" disabled selected style="display:none;">Тип приказа</option>
              <option value="1">Отпуск</option>
              <option value="2">Прием на работу</option>
              <option value="3">Увольнение</option>
            </select>-->
          </div>

          <div id="vacationFields" style="display: none;">
            <div class="form-group">
              <label for="vacationType">Выбор вида отпуска:</label>
              {{form.vacationType}}
              {{form.vacationType.errors}}
              <!--<select class="form-control" id="vacationType">
                <option value="" disabled selected style="display:none;">Вид отпуска</option>
                <option value="1">Ежегодный обычный</option>
                <option value="2">Ежегодный дополнительный</option>
                <option value="3">Без сохранения ЗП</option>
                <option value="4">Учебный</option>
              </select>-->
            </div>
            <div class="form-group">
              <label for="employee">Сотрудник:</label>
              {{form.employee}}
              {{form.employee.errors}}
            </div>
            <div class="form-group">
              <label for="startDate">Дата начала отпуска:</label>
              {{form.startDate}}
              {{form.startDate.errors}}
            </div>
            <div class="form-group">
              <label for="endDate">Дата окончания отпуска:</label>
              {{form.endDate}}
              {{form.endDate.errors}}
            </div>
          </div>
          <div id="hiringFields" style="display: none;">
            <div class="form-group">
              <label for="candidate">Кандидат:</label>
               {{form.candidate}}
              {{form.candidate.errors}}
            </div>
              <div class="form-group">
              <label>Оклад:</label>
               {{form.salary}}
              {{form.salary.errors}}
            </div>
               <div class="form-group">
            <label>Место работы:</label>
            {{form.pow}}
            {{form.pow.errors}}
          </div>
           <div class="form-group">
            <label>Подразделение:</label>
            {{form.subdivision}}
            {{form.subdivision.errors}}
          </div>
           <div class="form-group">
            <label>Должность:</label>
            {{form.job_title}}
            {{form.job_title.errors}}
          </div>
          </div>
          <div id="dismissalFields" style="display: none;">
            <div class="form-group">
              <label for="dismissalEmployee">Сотрудник:</label>
               {{form.dismissalEmployee}}
              {{form.dismissalEmployee.errors}}
            </div>
            <div class="form-group">
              <label for="reason">Причина увольнения:</label>
              {{form.reason}}
              {{form.reason.errors}}
            </div>
          </div>



          <button type="submit" name="addOrder" class="btn btn-primary">Добавить приказ</button>
        </form>
      </div>
      {% endif %}
    </div>

    <h1>Недавние приказы</h1>
    <ul class="list-group">
      {% if vacations_last|length == 0 and recruitments_last|length == 0 and dismissals_last|length == 0 %}
            <li class="list-group-item">Список пуст</li>
            {% else %}
                 {% for order in vacations_last %}
                    <li class="list-group-item"><a href="{{order.file.url}}" target="_blank">Приказ о предоставлении отпуска от {{order.receipt_date}}</a></li>
                {% endfor %}
                {% for order in recruitments_last %}
                    <li class="list-group-item"><a href="{{order.file.url}}" target="_blank">Приказ о приеме на работу от {{order.recruitment_date}}</a></li>
                {% endfor %}
                {% for order in dismissals_last %}
                    <li class="list-group-item"><a href="{{order.file.url}}" target="_blank">Приказ об увольнении от {{order.dismissal_date}}</a></li>
                {% endfor %}
            {% endif %}
    </ul>

    <h1>Все приказы</h1>
    <ul class="list-group">

        {% if all_vacations|length == 0 and all_recruitments|length == 0 and all_dismissals|length == 0 %}
            <li class="list-group-item">Список пуст</li>
            {% else %}
                 {% for order in all_vacations %}
                    <li class="list-group-item"><a href="{{order.file.url}}" target="_blank">Приказ о предоставлении отпуска от {{order.receipt_date}}</a></li>
                {% endfor %}
                {% for order in all_recruitments %}
                    <li class="list-group-item"><a href="{{order.file.url}}" target="_blank">Приказ о приеме на работу от {{order.recruitment_date}}</a></li>
                {% endfor %}
                {% for order in all_dismissals %}
                    <li class="list-group-item"><a href="{{order.file.url}}" target="_blank">Приказ об увольнении от {{order.dismissal_date}}</a></li>
                {% endfor %}
            {% endif %}
    </ul>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
    $('#id_orderType').change(function(){
      if ($(this).val() === "1") {
        $('#vacationFields').show();
        $('#hiringFields').hide();
        $('#dismissalFields').hide();
      } else if ($(this).val() === "2") {
        $('#vacationFields').hide();
        $('#hiringFields').show();
        $('#dismissalFields').hide();
      } else if ($(this).val() === "3") {
        $('#vacationFields').hide();
        $('#hiringFields').hide();
        $('#dismissalFields').show();
      }
    });
  </script>

</body>

</html>